crf:
  algorithm: "lbfgs"
  c1: 0.05
  c2: 0.01
  max_iterations: 500
  all_possible_transitions: true

svm:
  loss: "hinge"
  penalty: "l2"
  alpha: 0.00001
  max_iter: 2000
  random_state: 42

maxent:
  solver: "lbfgs"
  multi_class: "multinomial"
  max_iter: 2000
  C: 10.0
  random_state: 42

logistic_l1:
  solver: "liblinear" # liblinear hỗ trợ L1 tốt nhất
  penalty: "l1"
  max_iter: 2000
  C: 1.0
  random_state: 42