crf:
  algorithm: "lbfgs"
  c1: 0.05
  c2: 0.01
  max_iterations: 500
  all_possible_transitions: true

svm:
  vectorizer: "phobert"
  loss: "hinge"
  penalty: "l2"
  alpha: 0.00001
  max_iter: 2000
  random_state: 42

maxent:
  vectorizer: "phobert"
  solver: "lbfgs"
  multi_class: "multinomial"
  max_iter: 2000
  C: 10.0
  random_state: 42

random_forest:
  vectorizer: "phobert"
  n_estimators: 100
  criterion: "gini"
  max_depth: 20
  min_samples_split: 5
  n_jobs: -1
  random_state: 42